### ISSUE TITLE
several errors when installing/ starting your demo

### ISSUE THREAD

**Issue by inos-github** [solarkraft/lib-jitsi-meet-demo#1]
I am trying to run your demo (as an Typescript-Newbee) on Ubuntu 20.04 with nodejs v14.18.3
The goal is to use the video/audio tracks within an Vue 3 app. 
There are some missing dependencies with the given package.json so I had to add the following (however, I'm not sure about the correct versions...).
```
"@typed/disposable": "^3.4.1",
"tslib": "^2.3.1",
"ts-loader": "^9.2.6",
"typescript": "^4.5.4",
"webpack": "^5.66.0",
"webpack-dev-server": "^4.7.3"
```

after installing without further errors, I had to change JitsiMeet.ts:
```
- import JitsiConference from "@lyno/lib-jitsi-meet/JitsiConference";
- import JitsiConnection from "@lyno/lib-jitsi-meet/JitsiConnection";
+ import JitsiConference from "@lyno/lib-jitsi-meet/dist/JitsiConference";
+ import JitsiConnection from "@lyno/lib-jitsi-meet/dist/JitsiConnection";
```
starting the demo results in:
```
[tsl] ERROR in /..../lib-jitsi-meet-demo/src/JitsiMeet.ts(201,69)
      TS2345: Argument of type '(e: JitsiConnectionErrors) => void' is not assignable to parameter of type '() => unknown'.

[tsl] ERROR in /..../lib-jitsi-meet-demo/src/JitsiMeet.ts(202,64)
      TS2345: Argument of type '(e: JitsiConferenceErrors) => void' is not assignable to parameter of type '() => unknown'.

[tsl] ERROR in /..../lib-jitsi-meet-demo/src/JitsiMeet.ts(206,45)
      TS2345: Argument of type 'Function' is not assignable to parameter of type '() => unknown'.
  Type 'Function' provides no match for the signature '(): unknown'.

[tsl] ERROR in /..../lib-jitsi-meet-demo/src/JitsiMeet.ts(234,20)
      TS2339: Property 'xmpp' does not exist on type 'JitsiConnection'.

[tsl] ERROR in /..../lib-jitsi-meet-demo/src/JitsiMeet.ts(253,37)
      TS2554: Expected 1 arguments, but got 2.
```

Do you have any suggestions what I'm doing wrong and how to fix this?

**Comment by solarkraft** [comment]
Thanks for checking out my project and sorry about the issues. 

I have experienced an issue with lyno/-lib-jitsi-meet in which the solution was to re-install its npm packages (`(cd node_modules/@lyno/lib-jitsi-meet && npm install)`). 

I'm not exactly sure what exactly the issue is here, but it might help to know that lyno/lib-jitsi-meet has moved a bunch of classes around between recent releases.  I'm not exactly sure that your import changes make sense. 

I will have a closer look.

**Comment by inos-github** [comment]
Thanks for your looking into the issue!
Unfortunately reinstalling the module did not help and I still get the same error message.

**Comment by solarkraft** [comment]
Hey, I'm sorry in case you've been hoping for more support. I haven't been able to dedicate much resources to this project lately. I hope the code can still be useful to you even though you can not run it.

**Comment by solarkraft** [comment]
... better late than never? :-)

I'm now able to build it again (on a new machine).
